name: avora
description: "Avora"
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/avora/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/avora/logo.svg
    - assets/avora/icon.png